"""Stub file for reflex_ui/__init__.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------

from . import components, utils
from .components import base
from .components.base.avatar import avatar
from .components.base.badge import badge
from .components.base.button import button
from .components.base.card import card
from .components.base.checkbox import checkbox
from .components.base.dialog import dialog
from .components.base.gradient_profile import gradient_profile
from .components.base.input import input
from .components.base.link import link
from .components.base.menu import menu
from .components.base.navigation_menu import navigation_menu
from .components.base.popover import popover
from .components.base.preview_card import preview_card
from .components.base.scroll_area import scroll_area
from .components.base.select import select
from .components.base.skeleton import skeleton
from .components.base.slider import slider
from .components.base.switch import switch
from .components.base.tabs import tabs
from .components.base.textarea import textarea
from .components.base.theme_switcher import theme_switcher
from .components.base.toggle import toggle
from .components.base.toggle_group import toggle_group
from .components.base.tooltip import tooltip
from .components.icons.hugeicon import hi, icon
from .components.icons.others import spinner
from .utils.twmerge import cn

_REFLEX_UI_MAPPING = {
    "components.base.avatar": ["avatar"],
    "components.base.badge": ["badge"],
    "components.base.button": ["button"],
    "components.base.card": ["card"],
    "components.base.checkbox": ["checkbox"],
    "components.base.dialog": ["dialog"],
    "components.base.gradient_profile": ["gradient_profile"],
    "components.base.input": ["input"],
    "components.base.link": ["link"],
    "components.base.menu": ["menu"],
    "components.base.navigation_menu": ["navigation_menu"],
    "components.base.popover": ["popover"],
    "components.base.preview_card": ["preview_card"],
    "components.base.scroll_area": ["scroll_area"],
    "components.base.select": ["select"],
    "components.base.skeleton": ["skeleton"],
    "components.base.slider": ["slider"],
    "components.base.switch": ["switch"],
    "components.base.tabs": ["tabs"],
    "components.base.textarea": ["textarea"],
    "components.base.theme_switcher": ["theme_switcher"],
    "components.base.toggle_group": ["toggle_group"],
    "components.base.toggle": ["toggle"],
    "components.base.tooltip": ["tooltip"],
}
_SUBMODULES = {"components", "utils"}
_SUBMOD_ATTRS = {
    **_REFLEX_UI_MAPPING,
    "components": ["base"],
    "components.icons.hugeicon": ["hi", "icon"],
    "components.icons.others": ["spinner"],
    "utils.twmerge": ["cn"],
}

__all__ = [
    "avatar",
    "badge",
    "base",
    "button",
    "card",
    "checkbox",
    "cn",
    "components",
    "dialog",
    "gradient_profile",
    "hi",
    "icon",
    "input",
    "link",
    "menu",
    "navigation_menu",
    "popover",
    "preview_card",
    "scroll_area",
    "select",
    "skeleton",
    "slider",
    "spinner",
    "switch",
    "tabs",
    "textarea",
    "theme_switcher",
    "toggle",
    "toggle_group",
    "tooltip",
    "utils",
]
