fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        files: ^reflex_ui/
        args: ["--fix", "--exit-non-zero-on-fix", "--no-unsafe-fixes"]
      - id: ruff-format
        files: ^reflex_ui/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^reflex_ui/

  # Run pyi check before pyright because pyright can fail if pyi files are wrong.
  # - repo: local
  #   hooks:
  #     - id: update-pyi-files
  #       name: update-pyi-files
  #       always_run: true
  #       language: system
  #       require_serial: true
  #       description: "Update pyi files as needed"
  #       entry: python3 scripts/make_pyi.py

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        files: ^reflex_ui/
        language: system
