fail_fast: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff-format
        files: ^reflex_ui/
      - id: ruff
        files: ^reflex_ui/
        args: ["--fix", "--exit-non-zero-on-fix", "--no-unsafe-fixes"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^reflex_ui/

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
      - id: pyright
        files: ^reflex_ui/
        language: system
