"""Stub file for reflex_ui/components/base/__init__.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------

from reflex_ui import _REFLEX_UI_MAPPING

from .accordion import accordion
from .avatar import avatar
from .badge import badge
from .button import button
from .card import card
from .checkbox import checkbox
from .collapsible import collapsible
from .dialog import dialog
from .drawer import drawer
from .gradient_profile import gradient_profile
from .input import input
from .link import link
from .menu import menu
from .navigation_menu import navigation_menu
from .popover import popover
from .preview_card import preview_card
from .scroll_area import scroll_area
from .select import select
from .skeleton import skeleton
from .slider import slider
from .switch import switch
from .tabs import tabs
from .textarea import textarea
from .theme_switcher import theme_switcher
from .toggle import toggle
from .toggle_group import toggle_group
from .tooltip import tooltip

_SUBMODULES = set()
_SUBMOD_ATTRS = {
    "".join(k.split("components.base.")[-1]): v for k, v in _REFLEX_UI_MAPPING.items()
}

__all__ = [
    "accordion",
    "avatar",
    "badge",
    "button",
    "card",
    "checkbox",
    "collapsible",
    "dialog",
    "drawer",
    "gradient_profile",
    "input",
    "link",
    "menu",
    "navigation_menu",
    "popover",
    "preview_card",
    "scroll_area",
    "select",
    "skeleton",
    "slider",
    "switch",
    "tabs",
    "textarea",
    "theme_switcher",
    "toggle",
    "toggle_group",
    "tooltip",
]
